### ISSUE TITLE
Enable Github Pages

### ISSUE THREAD

**Issue by Lomilar** [jhaag75/xapi-ontology#1]
Even in draft form, having the resources included here in URL accessible form creates more capability to test interoperability.

For instance, being able to define an object:

`{
  "@context":"https://jhaag75.github.io/xapi-ontology/statement-context.jsonld",
  "@type":"Statement"
}`

is useful for testing drafts.

https://jhaag75.github.io/xapi-ontology/...

**Comment by jhaag75** [comment]
Thank you. Moving this over to the ADL repo and will set up pages there.
