### ISSUE TITLE
Flexibility of @id, id, and general ID wars.

### ISSUE THREAD

**Issue by Lomilar** [jhaag75/xapi-ontology#2]
Let me know if I am incorrect.

Currently, xAPI uses an UUID ID parameter (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#241-id)

RDF practice would be to convert this to a URN, as done in the example statement [here](https://raw.githubusercontent.com/jhaag75/xapi-ontology/master/statement-example-with-JSONLD-%40context-and-syntax.json).

However, [best practices](https://www.w3.org/TR/json-ld/#node-identifiers) are to have the JSON-LD @id be a IRI (and hopefully also a URL).

This separation of practice would lead me to recommend converting `"id":"@id"` in the context to 
`"id":{
"@id": "xapi:id",
"@type": "xsd:string"
}`

@id is kinda special to the Semantic Web and JSON-LD, so it's dangerous to map anything to it.

**Comment by jhaag75** [comment]
Yes, I noticed this too. Thanks for pointing this out. I never received notification of this issue for some reason. Updating the context to your recommendation. Thank you @Lomilar
